site_name: klartext/dossier

repo_url: https://github.com/klartext-dossier/klartext-dossier
docs_dir: website
site_dir: docs
use_directory_urls: false

theme:
  name: "material"
  features:
    - content.code.annotate
    - content.code.copy    

plugins:
- search
- mkdocstrings:
    handlers:
      python:
        options:
          show_root_heading: true
          show_source: false
    
markdown_extensions:
- admonition
- def_list
- attr_list
- md_in_html
- pymdownx.highlight:
    use_pygments: true
    anchor_linenums: true
    line_spans: __span
    pygments_lang_class: true
- pymdownx.inlinehilite
- pymdownx.snippets
- pymdownx.superfences
- pymdownx.tabbed:
    alternate_style: true

nav:
  - Overview: index.md
  - klartext:
    - Overview: klartext/index.md
    - Quickstart: klartext/quickstart.md
    - Manual: klartext/manual.md
    - API Reference: klartext/reference.md
  - htmlbook-mdx:
    - Overview: mdx/index.md
    - Quickstart: mdx/quickstart.md
    - API Reference: mdx/reference.md
  - htmlbook-css:
    - Overview: htmlbook/index.md
  - dm:
    - Overview: dm/index.md
    # - API Reference: dm/reference.md
