site_name: klartext/dossier

repo_url: https://github.com/klartext-dossier/klartext-dossier
docs_dir: website
site_dir: docs
use_directory_urls: false
exclude_docs: examples/

theme:
  name: "material"
  features:
    - content.code.annotate
    - content.code.copy    

plugins:
- search
- mkdocstrings:
    handlers:
      python:
        options:
          show_root_heading: true
          show_source: false
    
markdown_extensions:
- admonition
- def_list
- attr_list
- md_in_html
- pymdownx.highlight:
    use_pygments: true
    anchor_linenums: true
    line_spans: __span
    pygments_lang_class: true
- pymdownx.inlinehilite
- pymdownx.snippets
- pymdownx.superfences
- pymdownx.tabbed:
    alternate_style: true

nav:
  - Overview: index.md
  - klartext:
    - Overview: klartext/index.md
    - Quickstart: klartext/quickstart.md
    - Manual: klartext/manual.md
    - API Reference: klartext/reference.md
  - htmlbook-mdx:
    - Overview: mdx/index.md
    - Quickstart: mdx/quickstart.md
    - API Reference: mdx/reference.md
  - htmlbook-css:
    - Overview: htmlbook/index.md
    - Quickstart: htmlbook/quickstart.md
  - dm:
    - Overview: dm/index.md
    - Quickstart: dm/quickstart.md
    - Manual: 
      - Overview: dm/manual.md
      - file task: dm/task-file.md
      - include task: dm/task-include.md
      - load task: dm/task-load.md
      - markdown-include task: dm/task-markdown-include.md
      - code-highlight task: dm/task-code-highlight.md
      - copy task: dm/task-copy.md
      - diagram-to-svg task: dm/task-diagram-to-svg.md
      - embed-svg task: dm/task-embed-svg.md
      - klartext-to-xml task: dm/task-klartext-to-xml.md
      - markdown-to-xhtml task: dm/task-markdown-to-xhtml.md
      - pdf-to-png task: dm/task-pdf-to-png.md
    - API Reference: dm/reference.md
