site_name: klartext/dossier

repo_url: https://github.com/klartext-dossier/klartext-dossier
repo_name: klartext-dossier

docs_dir: website
site_dir: docs

use_directory_urls: false
exclude_docs: examples/

theme:
  name: "material"
  palette:
    - scheme: default
      toggle:
        icon: material/eye-outline
        name: Switch to dark mode
      primary: red
      accent: orange
    - scheme: slate
      toggle:
        icon: material/eye
        name: Switch to light mode
      primary: red
      accent: orange
  features:
    - content.code.annotate
    - content.code.copy    
    - navigation.tabs
    
plugins:
- search
- privacy
- git-revision-date-localized:
    enable_creation_date: true
    type: timeago
    fallback_to_build_date: true
- git-authors
- mkdocstrings:
    handlers:
      python:
        options:
          show_root_heading: true
          show_source: false
          heading_level: 3
        paths: [dm, klartext, mdx]
    
extra:
  generator: false
  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.  
    actions:
      - accept
      - manage       
    cookies:
      analytics:
        name: Google Analytics
        checked: false

copyright: >
  Copyright &copy; 2025 Matthias Hölzer-Klüpfel - <a href="#__consent">Change cookie settings</a> - Made with <a href="https://squidfunk.github.io/mkdocs-material/">Material</a> for <a href="https://www.mkdocs.org/">MkDocs</a>

markdown_extensions:
- admonition
- def_list
- attr_list
- md_in_html
- pymdownx.highlight:
    use_pygments: true
    anchor_linenums: true
    line_spans: __span
    pygments_lang_class: true
- pymdownx.inlinehilite
- pymdownx.snippets
- pymdownx.superfences
- pymdownx.tabbed:
    alternate_style: true

nav:
  - Home: 
    - Overview: index.md
    - klartext: klartext/index.md
    - htmlbook-mdx: mdx/index.md
    - htmlbook-css: htmlbook/index.md
    - dm: dm/index.md
  - klartext:
    - Overview: klartext/index.md
    - Quickstart: klartext/quickstart.md
    - Manual: klartext/manual.md
    - API Reference: klartext/reference.md
  - htmlbook-mdx:
    - Overview: mdx/index.md
    - Quickstart: mdx/quickstart.md
    - API Reference: mdx/reference.md
  - htmlbook-css:
    - Overview: htmlbook/index.md
    - Quickstart: htmlbook/quickstart.md
  - dm:
    - Overview: dm/index.md
    - Quickstart: dm/quickstart.md
    - Manual: 
      - Overview: dm/manual.md
      - code-highlight task: dm/task-code-highlight.md
      - copy task: dm/task-copy.md
      - diagram-to-svg task: dm/task-diagram-to-svg.md
      - dump task: dm/task-dump.md
      - embed-svg task: dm/task-embed-svg.md
      - file task: dm/task-file.md
      - if task: dm/task-if.md
      - include task: dm/task-include.md
      - klartext-to-xml task: dm/task-klartext-to-xml.md
      - load task: dm/task-load.md
      - markdown-include task: dm/task-markdown-include.md
      - markdown-to-xhtml task: dm/task-markdown-to-xhtml.md
      - pdf-to-png task: dm/task-pdf-to-png.md
      - pngs-to-pptx task: dm/task-pngs-to-pptx.md
      - save task: dm/task-save.md
      - sequence task: dm/task-sequence.md
      - xhtml-to-docx task: dm/task-xhtml-to-docx.md
      - xhtml-to-pdf task: dm/task-xhtml-to-pdf.md
      - xml-tidy task: dm/task-xml-tidy.md
      - xml-transform task: dm/task-xml-transform.md
      - xml-validate task: dm/task-xml-validate.md
    - API Reference:
      - Context: dm/api-context.md
      - Exceptions: dm/api-exceptions.md
      - LXML Extensions: dm/api-lxml-extensions.md
      - Main: dm/api-main.md   
      - Markdown Parser: dm/api-markdown-parser.md
      - Pipeline: dm/api-pipeline.md    
      - Run Command: dm/api-run-command.md    
      - Utilities: dm/api-utilities.md   
      - Task: dm/api-task.md   
      - Task Factory: dm/api-task-factory.md   
