site_name: Klartext Documentation
repo_url: https://dev.azure.com/hoelzer-kluepfel/_git/dossier

theme:
  name: "material"

plugins:
- search
- mkdocstrings:
    handlers:
      python:
        options:
          show_root_heading: true
          show_source: false

nav:
  - Overview: index.md
  - Reference: reference.md