name: Make all packages

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    container: node:16-bullseye
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Make packages
      run: make
