name: Make all packages

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: emhaka/pypeline:latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Make packages
      run: make
